apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alef-backend.fullname" . }}
  labels:
    {{- include "alef-backend.labels" . | nindent 4 }}
    app: angular-webapp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alef-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alef-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alef-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-app-configmap
                  key: MONGO_HOSTNAME
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongodb-app-configmap
                  key: MONGO_DB
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-app-secret
                  key: MONGO_USERNAME
            - name: MONGODB_PASSWORd
              valueFrom:
                secretKeyRef:
                  name: mongodb-app-secret
                  key: MONGO_PASSWORD   
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
              #livenessProbe:
              #httpGet:
              #path: /
              #port: http
              #readinessProbe:
              #httpGet:
              #path: /
              #port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
